# Archivo de configuración para Air

[build]
# Ruta del binario compilado
bin = "./tmp/main"

# Comando para compilar el proyecto
cmd = "go build -o ./tmp/main ./cmd/main.go"

# Nivel de logs
log = "debug"

# Extensiones de archivos a observar
include_ext = ["go", "tpl", "tmpl", "html"]

# Directorios a observar
include_dir = ["internal", "pkg", "cmd"]

# Directorios a excluir
exclude_dir = ["vendor", "tmp"]

# Archivos a excluir
exclude_file = ["*_test.go"]

[run]
# Comando para ejecutar el binario
cmd = "./tmp/main"

# Configuración de tiempo entre recompilaciones (en segundos)
delay = 1

[log]
# Formato de tiempo para los logs
time_format = "2006-01-02 15:04:05"
